### ISSUE TITLE
Investigate final differences between Figure 3 traces in paper, from XPP & LEMS

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/PinskyRinzelModel#10]
There seems to be minor differences in the shape of membrane potential traces between the paper & jNeuroML. Is it possible to make these differences go away with smaller time step?

**Comment by JustasB** [comment]
Was able to get a closer match by taking the second spike instead of the first. Take a look here: https://github.com/OpenSourceBrain/PinskyRinzelModel/commit/6ba475937cf36973ff1c0c5bcfdca04d39004ad3

**Comment by pgleeson** [comment]
Great.
