### ISSUE TITLE
Tidy up documentation

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/PinskyRinzelModel#11]
Update README with general structure:

Introduction 
- Overview of model 
- Physiological properties demonstrated (brief summary of properties of model & results)

Original model version (Move Victoria Booth's mail text to README of https://github.com/OpenSourceBrain/PinskyRinzelModel/tree/master/XPP/Victoria%20Booth%20code and link there)

NeuroML2/LEMS version
- Why?
- Installation instructions (based on http://www.opensourcebrain.org/projects/pinskyrinzelmodel/wiki)
  - Different versions (lems/dl/2comp)
  - Summary of props from paper shown by lems version
- Issues with conversion

**Comment by JustasB** [comment]
Implemented here: https://github.com/OpenSourceBrain/PinskyRinzelModel/pull/12

**Comment by pgleeson** [comment]
Great. Have made some minor changes.
