### ISSUE TITLE
Convert to 2 compartment model

### ISSUE THREAD

**Issue by JustasB** [OpenSourceBrain/PinskyRinzelModel#6]
From Padraig: Re the 2 compartment cell, you can base the impl on https://github.com/OpenSourceBrain/ACnet2/blob/master/neuroConstruct/generatedNeuroML2/bask.cell.nml. Use the soma/dend radii here. Ion Channels will have to be broken out into an ion channel for each current. Convert absolute vals for conductance to conductance densities based on the surface areas of the soma/dend. Changing the length of the dendrite will alter the coupling coefficient... Might be best to make a simple python script that takes in initial radii, soma length, target coupling coefficient (pp) & calculates the correct dendrite length to use...

**Comment by pgleeson** [comment]
Nice progress with this. There's probably more that can be done to use more of the core nml2 elements, but this is probably fine for now. Someone can pick this up and use it as the basis for another 2 compartment cell in LEMS.
